on: 
  push:
    branches:
      - master
jobs:
  # word:
  #   name: Output to Microsoft Word with pandoc
  pdf:
    name: Output to PDF with pandoc
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/latex:2.9.1.1
        with:
          entrypoint: /bin/sh
          args: 'echo %PATH && tlmgr install zref && pandoc --standalone -o output.pdf --pdf-engine xelatex docs/test.md'
