on: 
  push:
    branches:
      - master
jobs:
  # word:
  #   name: Output to Microsoft Word with pandoc
  pdf:
    name: Output to PDF with pandoc
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update && sudo apt-get install wkhtmltopdf
      - uses: docker://pandoc/core:2.9.1.1
        with:
            args: "--standalone -o output.pdf -t html docs/test.md"
