on: 
  push:
    branches:
      - master
jobs:
  # word:
  #   name: Output to Microsoft Word with pandoc
  pdf:
    name: Output to PDF with pandoc
    runs-on: ubuntu-18.04
    steps:
      - run: cwd
      - uses: docker://pandoc/core:2.9
        with:
            args: "./docs/patient-guide.md -o output.pdf -t html"
