on: 
  push:
    branches:
      - master
jobs:
  # word:
  #   name: Output to Microsoft Word with pandoc
  # pdf:
  #  name: Output to PDF with pandoc
  #  runs-on: ubuntu-18.04
  #  steps:
  #    - uses: docker://pandoc/core:2.9
  #      with:
  #          args: "docs/patient-guide.md -o output.pdf -t html"
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://pandoc/core:2.9
        with:
          args: "--help" # gets appended to pandoc command
